/**
 * Regenerate `src/css-colors.ts` from the CSS Color 4 named-color table.
 *
 *   bun run gen:colors
 *
 * The list is frozen by spec (last addition: rebeccapurple, 2014), so this is
 * a provenance tool, not a freshness one: run it to prove the checked-in
 * table matches the spec byte for byte.
 */

const SPEC = 'https://drafts.csswg.org/css-color-4/'

const res = await fetch(SPEC)
if (!res.ok) throw new Error(`${SPEC} answered ${res.status}`)
const html = await res.text()

// Each named-color row opens with two swatch cells:
// `<td style="background:name"> <td style="background:#rrggbb">`.
const colors = new Map<string, string>()
for (const m of html.matchAll(
  /<td style="background:([a-z]+)">\s*<td style="background:(#[0-9a-f]{6})">/g,
)) {
  colors.set(m[1], m[2])
}
if (colors.size !== 148) {
  throw new Error(`expected 148 named colors, parsed ${colors.size} — spec markup changed?`)
}

const rows = [...colors.entries()]
  .sort(([a], [b]) => (a < b ? -1 : 1))
  .map(([name, hex]) => `  ${name}: '${hex}',`)
  .join('\n')

const out = `// Generated by scripts/gen-css-colors.ts from ${SPEC} — do not edit.

/** The CSS Color 4 named-color table: name → \`#rrggbb\`. */
export const NAMED_COLORS: Record<string, string> = {
${rows}
}
`

const dest = new URL('../src/css-colors.ts', import.meta.url).pathname
await Bun.write(dest, out)
console.log(`wrote ${colors.size} colors to ${dest}`)
