// Emits the differential corpus consumed by `bun run differential`.
//
// Every hand-written test source, plus width and emoji edge cases, plus
// deterministic pseudo-random fuzz, each rendered at a spread of widths.
const HAND: string[] = [
  'graph TD\n A[Start] --> B[End]',
  'graph TD\n A-->|yes| B',
  'flowchart LR\n A --> B --> C --> D',
  'flowchart BT\n A[first] --> B[second] --> C[third]',
  'flowchart RL\n A[first] --> B[second] --> C[third]',
  'graph TD\n A[日本語ab]',
  'graph TD\n A[日本語ab] --> B[x]',
  'graph TD\n A[aaa] --> D[ddddddd]\n B[bb] --> D\n C[ccccc] --> D',
  'graph TD\n A[Check if the user has permission to access resource] --> B[Done]',
  'graph TD\n A[mark_filter_restore_context] --> B[Done]',
  'graph TD\n A ---|maybe| B',
  'graph TD\n A[aaaa] --> B[b] --> C[cccccccc]',
  'flowchart LR\n A <--> B',
  'graph TD\n A <--> B',
  'graph TD\n A <-- B',
  'graph TD\n A --> B\n B --> C\n A --> C',
  'graph TD\n C[ccc]\n D[ddd]\n A --> D\n B --> C',
  'graph TD\n A --> D[ddd]\n A --> C[ccc]\n B --> C\n B --> D',
  'graph TD\n A --> C[ccc]\n A --> D[ddd]',
  'graph TD\n A --> C[ccc]',
  'graph TD\n A --> B\n B --> C\n B --> A\n C --> A',
  'graph TD\n A --> B\n B --> C\n C --> A',
  'graph TD\n A --> B\n B --> C\n B --> A\n C --> B',
  'graph TD\n A --> B\n B --> C\n C --> B',
  'graph TD\n A & B --> C & D',
  'graph LR\n A & B --> C --> D',
  'graph TD\n A & B <-- C',
  'graph TD\n A --o B\n C --x D',
  'graph TD\n A o-- B\n C x-- D',
  'graph TD\n A <--o B\n C <--x D',
  'graph TD\n A o--o B\n C x--x D',
  'graph TD\n A -.-> B',
  'graph TD\n A ==> B',
  'graph LR\n A -. maybe .-> B',
  'graph TD\n A[aaaaaaa] ==> B\n A ==> C[ccccccc]',
  'graph TD\n A --> C\n B -.-> C',
  'graph TD\n A --> A',
  'graph TD\n A -->|again| A',
  'graph TD\n A --> A\n A --> B',
  'flowchart BT\n A --> A\n A --> B',
  'flowchart LR\n A --> A\n A --> B',
  'graph TD\n A -- no exit --> B',
  'graph TD\n A -- or else --> B',
  'graph TD\n A["wait; 50%% done"] --> B',
  'graph TD %% main flow\n A --> B %% trailing\n %% full line\n',
  'flowchart TD\n  A["<b>Bold</b> and <i>italic</i>"] --> B',
  'flowchart TD\n  A["Line1<br/>Line2<br>Line3"]',
  'flowchart TD\n  A["`**Start** here`"] --> B["`Save to **database**`"]\n  B --> C["`**Done!**`"]',
  'flowchart TD\n  A["`_italic_ uses `vocab_size` with __all__`"]',
  'flowchart TD\n  A -->|"`**yes**`"| B\n  A -->|"`__no__`"| C',
  'flowchart TD\n  A["[ 464, 3797 ] seq_len d_model"]',
  'flowchart TD\n  A["<code>vocab_size</code> <span style=\\"color:red\\">x</span>"]',
  'flowchart TD\n  A["a < b and c > d"]',
  'flowchart TD\n  A["Returns Vec<String>"] --> B["Option<i32> for <id>"]',
  'flowchart TD\n  IDs["<b>Token IDs</b><br/>[ 464, 3797 ]<br/><i>indices</i>"]',
  'flowchart TD\n  A[5" pipe] --> B[24" display]',
  'flowchart TD\n  A["Tokenizer (BPE / WordPiece)"] --> B[Done]',
  'flowchart TD\n  IDs["<b>3. Token IDs</b><br/>[ 464, 3797 ]<br/><i>indices</i>"] --> Out["<b>done</b>"]',
  'flowchart LR\n  YAML["models-config/&lt;model&gt;/&lt;env&gt;.yaml\\nenterprise_api_config:"]\n  PY["model_config_map.py"]\n  YAML --> PY',
  'graph TD\n S[Start] --> one\n subgraph one [Group One]\n A --> B\n end\n one --> E[End]',
  'graph TD\n subgraph api [API]\n A1 --> A2\n end\n subgraph db [Storage]\n B1\n end\n api --> db',
  'graph TD\n subgraph outer [Outer]\n subgraph inner [Inner]\n X --> Y\n end\n W --> X\n end\n S --> outer',
  'graph LR\n S --> A\n subgraph g [Workers]\n A --> B\n end\n B --> T',
  'graph TD\n X --> two\n subgraph two\n C --> D\n end',
  'graph TD\n subgraph "My Stuff"\n A\n end\n S --> A',
  'graph TD\n subgraph batch jobs\n B\n end\n S --> B',
  'graph TD\n subgraph "a &lt;b&gt;"\n C\n end\n S --> C',
  'graph TD\n subgraph ghost\n end\n A --> B',
  'flowchart BT\n S --> one\n subgraph one [Up]\n A --> B\n end',
  'stateDiagram-v2\n [*] --> Idle\n Idle --> Running: start\n Running --> [*]',
  'stateDiagram\n A --> B',
  'stateDiagram-v2\n A --> B',
  'stateDiagram-v2\n state "Waiting for input" as W\n W --> Done',
  'stateDiagram-v2\n state c <<choice>>\n A --> c\n c --> B: yes\n c --> D: no',
  'stateDiagram-v2\n s2 : waits patiently\n A --> s2',
  'stateDiagram-v2\n direction LR\n A --> B --> C',
  'stateDiagram-v2\n state Active {\n A --> B\n }\n Active --> Done',
  'stateDiagram-v2\n A --> B\n note right of A: inline note\n note left of B\n block text\n end note',
  'stateDiagram-v2\n A --> B\n B --> C\n C --> B: retry',
  'stateDiagram-v2\n A --> B\n some garbage line',
  'stateDiagram-v2\n A ---> B',
  'stateDiagram-v2\n state c <<choice>>\n c : pick a path\n A --> c\n c --> B',
  'stateDiagram-v2\n A --> B --> C',
  'stateDiagram-v2\n [*] --> A --> B: done',
  'stateDiagram-v2\n A --> B -->',
  'classDiagram\n class Animal {\n +int age\n +isMammal() bool\n }\n Animal <|-- Duck',
  'classDiagram\n Animal <|-- Duck\n Animal <|-- Fish',
  'classDiagram\n IShape <|.. Circle',
  'classDiagram\n Car *-- Engine\n Pond o-- Duck',
  'classDiagram\n class Duck {\n +swim()\n }\n Duck : +String beakColor\n S --> Duck',
  'classDiagram\n <<interface>> Shape\n Shape <|.. Circle',
  'classDiagram\n Shape~T~ : +area() T\n S --> Shape~T~',
  'classDiagram\n Student "many" --> "1" School : attends',
  'classDiagram\n Animal <|-- Duck\n Animal <|-- Fish\n Animal <|-- Cow',
  'classDiagram\n class Loner\n A --> Loner',
  'classDiagram\n A --> B\n total garbage here',
  'classDiagram\n direction LR\n A --> B',
  'classDiagram\n A ..> B',
  'erDiagram\n CUSTOMER ||--o{ ORDER : places\n CUSTOMER {\n string name PK "full name"\n int custNumber\n }',
  'erDiagram\n A ||..o{ B : uses',
  'erDiagram\n A ||--o{ B : has',
  'erDiagram\n p[Person] ||--o{ a["Bank Account"] : owns',
  'erDiagram\n LONER\n A ||--|| B : linked',
  'erDiagram\n A ||--|| B : ok\n utter nonsense statement',
  'sequenceDiagram\n Alice->>Bob: Hello Bob\n Bob-->>Alice: Hi Alice',
  'sequenceDiagram\n participant C as Client\n participant S as Server\n C->>S: GET /',
  'sequenceDiagram\n participant B\n participant A\n A->>B: hi',
  'sequenceDiagram\n A->>A: think',
  'sequenceDiagram\n A-x B: lost',
  'sequenceDiagram\n A->>B: hi\n Note over A,B: happy path',
  'sequenceDiagram\n autonumber\n A->>B: one\n B->>A: two',
  'sequenceDiagram\n A->>B: hi\n loop retry x3\n A->>B: again\n end',
  'sequenceDiagram\n rect rgb(0,0,0)\n A->>B: hi\n end',
  'sequenceDiagram\n loop l1\n box g\n participant A\n end\n A->>B: hi\n A->>B: bye\n end',
  'sequenceDiagram\n critical connect\n A->>B: try\n option timeout\n A->>A: log\n end',
  'sequenceDiagram\n A->>B: a very long message label that needs room\n B-->>A: ok',
  'sequenceDiagram\n ->>B: orphan',
  'sequenceDiagram\n A->>B: hi\n garbage statement here',
  'sequenceDiagram\n A->>+B: call\n B-->>-A: return',
  'sequenceDiagram\n Alice->>Bob: hi\n Note over Alice: solo note',
  'sequenceDiagram\n A->>B: hi\n Note left of A: L\n Note right of B: R',
  'gantt\n title Plan\n section A\n task :a1, 2024-01-01, 30d',
  'gantt\n title a very long line that should wrap inside the fallback box nicely',
  'flowchart LR\n A[aaaaaaaaaaaaaaaaaaaa] --> B[bbbbbbbbbbbbbbbbbbbb] --> C[cccccccccccccccccccc]',
  // whitespace / newline edge cases where a port most easily diverges
  'gantt\n title Plan\n a\n',
  'gantt\ntrailing\n\n\n',
  '\n\ngantt\nlead\n',
  'graph TD\n A --> B\n',
  'graph TD\r\n A --> B\r\n',
  'gantt\r\n title x\r\n',
  'graph TD\n A --> B\n\n\n',
  'pie\n title x\n "a" : 10',
  'mindmap\n root\n  a\n  b',
  'timeline\n a : b',
]

// Deterministic PRNG, so a failing case is always reproducible.
let seed = 987654321
const rnd = () => {
  seed = (seed * 1103515245 + 12345) & 0x7fffffff
  return seed / 0x7fffffff
}
const pick = <T>(a: T[]): T => a[Math.floor(rnd() * a.length)]
const HEADERS = [
  'graph TD',
  'graph LR',
  'flowchart BT',
  'flowchart RL',
  'stateDiagram-v2',
  'classDiagram',
  'erDiagram',
  'sequenceDiagram',
  'gantt',
  '',
]
const TOKENS: string[] = [
  'A',
  'B[x]',
  'C{d}',
  '-->',
  '<--',
  '-.->',
  '==>',
  '--o',
  '--x',
  '|lbl|',
  '&',
  'subgraph g',
  'end',
  '[*]',
  '<<choice>>',
  'A : m',
  '||--o{',
  ':',
  ';',
  '"q"',
  '%%',
  '~T~',
  '<b>',
  '&lt;',
  '日本',
  '🙂',
  '->>',
  '-->>',
  'Note over A,B: n',
  'loop x',
  'participant P as Q',
  'state "s" as S',
  '{',
  '}',
  '(',
  ')',
  '[',
  ']',
  '\n',
  '  ',
  '\t',
  '-',
  '=',
  '.',
  '<',
  '>',
  'o',
  'x',
  '*',
  '..|>',
  '__',
  '`',
  '\\',
  'A ||--|| B : x',
  'o--',
  '<|--',
  '[*] --> A',
]

// Width edge cases: control chars, zero-width marks, wide glyphs.
const SH = '­',
  ZWSP = '​',
  ACUTE = '́',
  ZWJ = '‍'
HAND.push(
  `graph TD\n A[a${SH}b] --> B[x]`,
  `graph TD\n A[${SH}${SH}${SH}] --> B`,
  `graph TD\n A[a${ZWSP}b] --> B`,
  `graph TD\n A[e${ACUTE}xyz] --> B`,
  `graph TD\n A[tab\there] --> B`,
  'graph TD\n A[a\tb\tc] --> B[d\te]',
  `gantt\n a\tb\n c${SH}d\n e${ZWSP}f`,
  'gantt\n\t\t\n\t',
  `graph TD\n A[日本語ab] --> B[한글${SH}x]`,
  'graph TD\n A[🙂🙂🙂] --> B[x]',
  `graph TD\n A[👨${ZWJ}👩${ZWJ}👧] --> B`,
  `sequenceDiagram\n A->>B: a\tb\n Note over A: ${SH}note`,
  `classDiagram\n class T {\n +a\tb\n +c${SH}d\n }\n T <|-- U`,
  `erDiagram\n E {\n string a\tb\n }\n E ||--|| F : x`,
  `stateDiagram-v2\n A --> B: a\tb`,
  `graph TD\n A[${'x'.repeat(30)}\t${'y'.repeat(30)}] --> B`,
)
TOKENS.push(SH, ZWSP, ACUTE, 'A[a\tb]', `A[${SH}]`, '日本語', '🙂')

// Emoji presentation sequences: ZWJ joins, modifiers, VS16, keycaps, flags.
const EMO = [
  '\u{1F468}',
  '\u{1F468}\u{200D}\u{1F469}',
  '\u{1F468}\u{200D}\u{1F469}\u{200D}\u{1F467}',
  '\u{1F469}\u{200D}\u{1F4BB}',
  '\u{1F44D}\u{1F3FD}',
  '\u{1F44D}\u{1F3FF}',
  '\u{2764}',
  '\u{2764}\u{FE0F}',
  '\u{26A0}\u{FE0F}',
  '\u{2705}',
  '1\u{FE0F}\u{20E3}',
  '\u{1F1EC}\u{1F1E7}',
  '\u{1F1EC}\u{1F1E7}\u{1F1EC}',
  '\u{200D}\u{1F469}',
  '\u{1F468}\u{200D}',
  'a\u{200D}b',
  '\u{1F468}\u{200D}a',
  'a\u{200D}\u{1F468}',
  '\u{65E5}\u{200D}\u{672C}',
  '\u{1F3F3}\u{FE0F}\u{200D}\u{1F308}',
  '\u{1F9D1}\u{200D}\u{1F692}',
]
for (const e of EMO) {
  HAND.push(`graph TD\n A[${e}] --> B[x]`)
  HAND.push(`graph LR\n A[pre ${e} post] --> B[${e}${e}]`)
  HAND.push(`sequenceDiagram\n A->>B: ${e} msg\n Note over A,B: ${e}`)
  HAND.push(`classDiagram\n class C {\n +f() ${e}\n }\n C <|-- D`)
  HAND.push(`erDiagram\n E {\n string ${e}\n }\n E ||--|| F : ${e}`)
  HAND.push(`stateDiagram-v2\n A --> B: ${e}`)
  HAND.push(`gantt\n title ${e}\n body ${e} more`)
  HAND.push(`graph TD\n A[${e.repeat(8)}] --> B`)
}
TOKENS.push(...EMO)

const WIDTHS = ['none', '1', '3', '8', '12', '20', '40', '80', '120', '200']
const out: string[] = []
const esc = (s: string) =>
  s.replace(/\\/g, '\\\\').replace(/\n/g, '\\n').replace(/\r/g, '\\r').replace(/\t/g, '\\t')
const add = (w: string, src: string) => out.push(`${w}\t${esc(src)}`)

for (const src of HAND) for (const w of WIDTHS) add(w, src)
for (let i = 0; i < 4000; i++) {
  const n = 1 + Math.floor(rnd() * 20)
  let src = `${pick(HEADERS)}\n`
  for (let k = 0; k < n; k++) src += pick(TOKENS) + (rnd() < 0.3 ? '\n' : ' ')
  add(pick(WIDTHS), src)
}
await Bun.write(new URL('corpus.txt', import.meta.url), `${out.join('\n')}\n`)
console.log(`${out.length} cases`)
