/**
 * Regenerates `src/width-data.ts`.
 *
 *   bun run gen:width      (requires a Rust toolchain)
 *
 * Per-code-point widths come from the `unicode-width` crate itself, via the
 * oracle in `tools/width-oracle` — the same crate, at the same version, that
 * the Rust renderer we are porting uses. Deriving them from the UCD by hand
 * gets the common cases right and the tail wrong (U+17D8 is three columns
 * wide, U+2D7F is one despite being a combining mark, and the zero-width set
 * is `Default_Ignorable ∪ Grapheme_Extend ∪ …`, not `Mn|Me|Cf`).
 *
 * EMOJI is Extended_Pictographic, read from the engine's own Unicode tables.
 * It drives the string-level ZWJ rule, which the oracle cannot express.
 */

const MAX_CP = 0x10ffff

type Range = [number, number]

/** Run the oracle, returning `[lo, hi, charWidth, strWidth]` runs. */
async function oracleRuns(): Promise<[number, number, number, number][]> {
  const proc = Bun.spawn(['cargo', 'run', '--release', '-q'], {
    cwd: new URL('../tools/width-oracle', import.meta.url).pathname,
    stdout: 'pipe',
    stderr: 'inherit',
  })
  const text = await new Response(proc.stdout).text()
  if ((await proc.exited) !== 0) throw new Error('width-oracle failed')

  return text
    .split('\n')
    .filter((l) => l !== '')
    .map((l) => {
      const [lo, hi, cw, sw] = l.split(' ')
      return [Number.parseInt(lo, 16), Number.parseInt(hi, 16), Number(cw), Number(sw)] as [
        number,
        number,
        number,
        number,
      ]
    })
}

/** Collapse a sorted code point list into inclusive ranges. */
function toRanges(codePoints: number[]): Range[] {
  const out: Range[] = []
  for (const cp of codePoints) {
    const last = out[out.length - 1]
    if (last && cp === last[1] + 1) last[1] = cp
    else out.push([cp, cp])
  }
  return out
}

/**
 * Extended_Pictographic: the set `unicode-width` treats as emoji when deciding
 * whether a ZWJ fuses two code points into one cluster.
 */
function emojiRanges(): Range[] {
  const pictographic = /\p{Extended_Pictographic}/u
  const out: number[] = []
  for (let cp = 0; cp <= MAX_CP; cp++) {
    if (pictographic.test(String.fromCodePoint(cp))) out.push(cp)
  }
  return toRanges(out)
}

const runs = await oracleRuns()
const widthRuns = runs
  .map(([lo, hi, cw, sw]) => `  [0x${lo.toString(16)}, 0x${hi.toString(16)}, ${cw}, ${sw}],`)
  .join('\n')
const emoji = emojiRanges()
  .map(([lo, hi]) => `  [0x${lo.toString(16)}, 0x${hi.toString(16)}],`)
  .join('\n')

await Bun.write(
  new URL('../src/width-data.ts', import.meta.url),
  `// Generated by scripts/gen-width-data.ts. Do not edit.
//
// WIDTHS covers the whole code point space as sorted, contiguous runs of
// [lo, hi, charWidth, strWidth], taken from the unicode-width crate.
// charWidth is \`UnicodeWidthChar::width(c).unwrap_or(0)\`; strWidth is the
// width of that character alone in a string. They differ: a tab is 0 and 1.
export const WIDTHS: [number, number, number, number][] = [
${widthRuns}
]

// Extended_Pictographic, for the string-level ZWJ clustering rule.
export const EMOJI: [number, number][] = [
${emoji}
]
`,
)

console.log(
  `wrote src/width-data.ts (${runs.length} width runs, ${emojiRanges().length} emoji ranges)`,
)
