/**
 * Regenerates `src/width-data.ts`.
 *
 *   bun run gen:width
 *
 * WIDE comes from the UCD's EastAsianWidth.txt (properties `W` and `F`,
 * including the `@missing` defaults that make unassigned CJK planes wide).
 * ZERO is derived from the running engine's Unicode tables via `\p{Mn}`,
 * `\p{Me}` and `\p{Cf}`, plus conjoining Hangul jamo, which have no combining
 * category but consume no width.
 *
 * Both match `unicode-width`, the crate the Rust original uses.
 */

const EAW_URL = 'https://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt'
const MAX_CP = 0x10ffff

type Range = [number, number]

/** Collapse a sorted code point list into inclusive ranges. */
function toRanges(codePoints: number[]): Range[] {
  const out: Range[] = []
  for (const cp of codePoints) {
    const last = out[out.length - 1]
    if (last && cp === last[1] + 1) last[1] = cp
    else out.push([cp, cp])
  }
  return out
}

/** Parse `XXXX;W` and `XXXX..YYYY;W` data lines plus `# @missing:` defaults. */
function parseEastAsianWidth(text: string): Range[] {
  const explicit = new Map<number, string>()
  const defaults: { range: Range; prop: string }[] = []

  for (const line of text.split('\n')) {
    const missing = line.match(/^#\s*@missing:\s*([0-9A-F]+)\.\.([0-9A-F]+)\s*;\s*(\w+)/i)
    if (missing) {
      defaults.push({
        range: [Number.parseInt(missing[1], 16), Number.parseInt(missing[2], 16)],
        prop: missing[3],
      })
      continue
    }
    const data = line.replace(/#.*$/, '').trim()
    if (data === '') continue
    const m = data.match(/^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*(\w+)$/i)
    if (!m) throw new Error(`unparsed EastAsianWidth line: ${line}`)
    const lo = Number.parseInt(m[1], 16)
    const hi = m[2] ? Number.parseInt(m[2], 16) : lo
    for (let cp = lo; cp <= hi; cp++) explicit.set(cp, m[3])
  }

  // Later @missing lines override earlier ones for overlapping ranges.
  const fallbackFor = (cp: number): string => {
    let prop = 'N'
    for (const d of defaults) if (cp >= d.range[0] && cp <= d.range[1]) prop = d.prop
    return prop
  }

  const wide: number[] = []
  for (let cp = 0; cp <= MAX_CP; cp++) {
    const prop = explicit.get(cp) ?? fallbackFor(cp)
    if (prop === 'W' || prop === 'F') wide.push(cp)
  }
  return toRanges(wide)
}

function zeroWidthRanges(): Range[] {
  // Cf covers ZWJ/ZWNJ/ZWSP and the bidi controls. SOFT HYPHEN is Cf but
  // occupies a column in a terminal, so unicode-width gives it 1 — match that.
  const combining = /\p{Mn}|\p{Me}|\p{Cf}/u
  const zero: number[] = []
  for (let cp = 0; cp <= MAX_CP; cp++) {
    if (cp === 0x00ad) continue
    // Conjoining jamo compose onto the preceding syllable block.
    if (cp >= 0x1160 && cp <= 0x11ff) {
      zero.push(cp)
      continue
    }
    if (combining.test(String.fromCodePoint(cp))) zero.push(cp)
  }
  return toRanges(zero)
}

function format(name: string, ranges: Range[]): string {
  const body = ranges
    .map(([lo, hi]) => `[0x${lo.toString(16)}, 0x${hi.toString(16)}],`)
    .join('\n  ')
  return `export const ${name}: [number, number][] = [\n  ${body}\n]\n`
}

const res = await fetch(EAW_URL)
if (!res.ok) throw new Error(`${EAW_URL} -> ${res.status}`)
const eaw = await res.text()
const version = eaw.match(/^# EastAsianWidth-([\d.]+)\.txt/)?.[1] ?? 'unknown'

const header = `// Generated by scripts/gen-width-data.ts from Unicode ${version}. Do not edit.
// Inclusive [lo, hi] code point ranges, sorted and non-adjacent.

`

await Bun.write(
  new URL('../src/width-data.ts', import.meta.url),
  header + format('WIDE', parseEastAsianWidth(eaw)) + '\n' + format('ZERO', zeroWidthRanges()),
)

console.log(`wrote src/width-data.ts from Unicode ${version}`)
