/**
 * Regenerates `src/width-data.ts`.
 *
 *   bun run gen:width      (requires a Rust toolchain)
 *
 * Per-code-point widths come from the `unicode-width` crate itself, via the
 * oracle in `tools/width-oracle`. Deriving them from the UCD by hand gets the
 * common cases right and the tail wrong (U+17D8 is three columns wide, U+2D7F
 * is one despite being a combining mark, and the zero-width set is
 * `Default_Ignorable ∪ Grapheme_Extend ∪ …`, not `Mn|Me|Cf`).
 *
 * Only the per-character column is used. Grapheme clustering — which is what
 * makes emoji measure correctly — comes from `Intl.Segmenter` at runtime, not
 * from a table here.
 */

/** Run the oracle, returning `[lo, hi, charWidth, strWidth]` runs. */
async function oracleRuns(): Promise<[number, number, number, number][]> {
  const proc = Bun.spawn(['cargo', 'run', '--release', '-q'], {
    cwd: new URL('../tools/width-oracle', import.meta.url).pathname,
    stdout: 'pipe',
    stderr: 'inherit',
  })
  const text = await new Response(proc.stdout).text()
  if ((await proc.exited) !== 0) throw new Error('width-oracle failed')

  return text
    .split('\n')
    .filter((l) => l !== '')
    .map((l) => {
      const [lo, hi, cw, sw] = l.split(' ')
      return [Number.parseInt(lo, 16), Number.parseInt(hi, 16), Number(cw), Number(sw)] as [
        number,
        number,
        number,
        number,
      ]
    })
}

// Take the string column, not the per-character one. They differ exactly where
// it matters for measuring: a tab is 1 here and 0 there, a soft hyphen 0 here
// and 0 there, a lone combining mark 0. Merge runs that agree once the other
// column is dropped.
const runs = await oracleRuns()
const merged: [number, number, number][] = []
for (const [lo, hi, , sw] of runs) {
  const last = merged[merged.length - 1]
  if (last && last[2] === sw && last[1] === lo - 1) last[1] = hi
  else merged.push([lo, hi, sw])
}

const body = merged
  .map(([lo, hi, w]) => `  [0x${lo.toString(16)}, 0x${hi.toString(16)}, ${w}],`)
  .join('\n')

await Bun.write(
  new URL('../src/width-data.ts', import.meta.url),
  `// Generated by scripts/gen-width-data.ts. Do not edit.
//
// Sorted, contiguous [lo, hi, width] runs covering the whole code point space:
// the width of that code point alone in a string, per the unicode-width crate.
// Grapheme clustering lives in width.ts, not here.
export const WIDTHS: [number, number, number][] = [
${body}
]
`,
)

console.log(`wrote src/width-data.ts (${merged.length} runs, from ${runs.length} oracle runs)`)
